# We are using the wrapper of a higher Gradle version (8.0.2),
# but it should be fine, since the wrapper will install the necessary Gradle version
image: gradle:7.6.0-jdk19-alpine

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  script:
    - ./gradlew build --info
    # preserve coverage information in an easy-to-reach folder
    - mv build/reports/jacoco/testCodeCoverageReport/html ./coverage
    - mv build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    paths:
      - ./coverage
  # As far as I understand, this specifies a Regex that will be used to find the test coverage
  # report by Jacoco, which has been printed to sout
  coverage: /TestCoverage:(\d+)%/
